all: mainp prod kons
mainp: mainp.o 
	gcc -o mainp mainp.o 
mainp.o: mainp.c
	gcc -c mainp.c
prod: prod.o 
	gcc -o prod prod.o 
prod.o: prod.c
	gcc -c prod.c 
kons: kons.o 
	gcc -o kons kons.o 
kons.o:	kons.c
	gcc -c kons.c

